name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      PUBLIC_GPG_KEY: ${{ secrets.PUBLIC_GPG_KEY }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build pytest

      - name: Run tests
        run: python -m pytest

      - name: Build distributions
        run: python -m build

      - name: Import maintainer public key
        run: |
          echo "$PUBLIC_GPG_KEY" > maintainer.asc
          gpg --import maintainer.asc
          gpg --list-keys

      - name: Verify tag signature
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          echo "Verifying signature of $TAG"
          git tag -v "$TAG"

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
