name: Release

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version to use'
        required: false
        default: '3.x'
        type: string
      windows-entry-script:
        description: 'Entry script for PyInstaller (Windows build); leave empty to skip'
        required: false
        default: ''
        type: string
      windows-exe-name:
        description: 'Name for the Windows executable'
        required: false
        default: 'common_utils'
        type: string
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ github.event.inputs.python-version || '3.x' }}

      - name: Set up uv
        uses: astral-sh/setup-uv@v1

      - name: Set up virtual environment
        run: uv venv

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            uv pip install -r requirements.txt
          elif [ -f pyproject.toml ]; then
            uv pip install -e .
          fi
          uv pip install build pytest

      - name: Run tests
        run: |
          if [ -d tests ]; then uv run pytest; else echo 'No tests to run'; fi

      - name: Build distributions
        run: uv run python -m build

      - name: Install cosign
        uses: sigstore/cosign-installer@v3

      - name: Sign artifacts
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: |
          for file in dist/*; do
            cosign sign-blob --yes "$file" \
              --output-signature "$file.sig" \
              --output-certificate "$file.pem"
          done

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: dist/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  windows-exe:
    runs-on: windows-latest
    permissions:
      contents: write
      id-token: write
    defaults:
      run:
        shell: bash
    env:
      WINDOWS_ENTRY_SCRIPT: ${{ github.event.inputs.windows-entry-script || '' }}
      WINDOWS_EXE_NAME: ${{ github.event.inputs.windows-exe-name || 'common_utils' }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ github.event.inputs.python-version || '3.x' }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pytest tomli
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          elif [ -f pyproject.toml ]; then
            pip install -e .
          fi

      - name: Run tests
        run: |
          if [ -d tests ]; then pytest; else echo 'No tests to run'; fi

      - name: Detect entry script
        run: |
          entry="$WINDOWS_ENTRY_SCRIPT"
          if [ -z "$entry" ]; then
            entry=$(python .github/scripts/detect_entry.py)
          fi
          if [ -z "$entry" ] && [ "$GITHUB_EVENT_NAME" = "push" ]; then
            entry="src/common_utils/bitwarden.py"
          fi
          echo "WINDOWS_ENTRY_SCRIPT=$entry" >> "$GITHUB_ENV"

      - name: Build executable
        if: env.WINDOWS_ENTRY_SCRIPT != ''
        run: pyinstaller --onefile -n "$WINDOWS_EXE_NAME" "$WINDOWS_ENTRY_SCRIPT"

      - name: Install cosign
        if: ${{ hashFiles(format('dist/{0}.exe', env.WINDOWS_EXE_NAME)) != '' }}
        uses: sigstore/cosign-installer@v3

      - name: Sign executable
        if: ${{ hashFiles(format('dist/{0}.exe', env.WINDOWS_EXE_NAME)) != '' }}
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: |
          cosign sign-blob --yes dist/${{ env.WINDOWS_EXE_NAME }}.exe \
            --output-signature dist/${{ env.WINDOWS_EXE_NAME }}.exe.sig \
            --output-certificate dist/${{ env.WINDOWS_EXE_NAME }}.exe.pem

      - name: Upload Windows assets
        if: ${{ hashFiles(format('dist/{0}.exe', env.WINDOWS_EXE_NAME)) != '' }}
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/${{ env.WINDOWS_EXE_NAME }}.exe
            dist/${{ env.WINDOWS_EXE_NAME }}.exe.sig
            dist/${{ env.WINDOWS_EXE_NAME }}.exe.pem
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
