name: Release

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version to use'
        required: false
        default: '3.x'
        type: string
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ github.event.inputs.python-version || '3.x' }}

      - name: Set up uv
        uses: astral-sh/setup-uv@v1

      - name: Set up virtual environment
        run: uv venv

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then uv pip install -r requirements.txt; fi
          uv pip install build pytest

      - name: Run tests
        run: |
          if [ -d tests ]; then uv run pytest; else echo 'No tests to run'; fi

      - name: Build distributions
        run: uv run python -m build

      - name: Install cosign
        uses: sigstore/cosign-installer@v3

      - name: Sign artifacts
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: |
          for file in dist/*; do
            cosign sign-blob --yes "$file" \
              --output-signature "$file.sig" \
              --output-certificate "$file.pem"
          done

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: dist/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
